language: node_js
sudo: false
node_js:
  - 0.10
install:
  - npm install bower gulp phantomjs -g
  - npm install
  - bower install 
script:
  - gulp less
  - gulp bundle
  - gulp test-make
  - node test/main.js -b phantomjs
before_deploy:
- cp -r public slamdata
- tar cjf slamdata.tar.bz2 slamdata
deploy:
  provider: releases
  api-key:
    secure: TitL0gINR0xhcMdNBSFKulH7VlS+q1bAkmkWe5H5drTGesqFQprmnoHxPM8Sstfr0DGrAsSKweN/SsUpmVpK8fUE3AcK9kNqt9HXIXr2UotYa1f3jqQKc4+KRXOOf4qjEdUwYRYYMUayR4psA/mijm3WxoVG/jrOjRZAkal/NAY=
  file: slamdata.tar.bz2
  skip_cleanup: true
  on:
    repo: slamdata/slamdata
    branch: master
    tags: true
notifications:
  slack:
    secure: EbxkmDGMm5b2K5tpFrcjEmywSzhU6TSJM6VuCzIfpZ78UWqxQ6u2bbpL5a7FYjYqLZI4U/+7p+M85o0Sj58KHgfwWtpgJn84uKvIkSHo808LU/zmCBuiY4kB4z5AnTXVVFdJ2Lx+vjaeBvZA0XNztdDAViT0QM0nTAs7T94oAW8=
